import { useRef, useState } from 'react'
import { AlertTriangle, ArrowLeft, Camera, CheckCircle2, ChevronRight, Clock3, HardHat, LogOut, MapPin, Navigation, ShieldCheck, Truck, Upload, UsersRound } from 'lucide-react'
import { Button } from '../../components/ui/Button'
import { PriorityBadge, StatusBadge } from '../../components/ui/Badge'
import { DemoBar } from '../../components/DemoBar'
import { Logo } from '../../components/brand/Logo'
import { useAuth } from '../../context/AuthContext'
import { useData } from '../../context/DataContext'
import { fileToDataUrl, formatStatus, pct, timeAgo } from '../../lib/utils'
import type { CleanupVerification, Incident, IncidentStatus } from '../../types/domain'

const nextAction:Partial<Record<IncidentStatus,{next:IncidentStatus;label:string}>>={ASSIGNED:{next:'ACCEPTED',label:'ACCEPT ASSIGNMENT'},ACCEPTED:{next:'DISPATCHED',label:'START TRAVEL'},DISPATCHED:{next:'ON_SITE',label:'MARK ON SITE'},ON_SITE:{next:'CLEANUP_IN_PROGRESS',label:'START CLEANUP'},CLEANUP_IN_PROGRESS:{next:'CLEANUP_COMPLETED',label:'COMPLETE CLEANUP'}}
export function FieldWorkerApp(){const {profile,signOut}=useAuth();const data=useData();const [selected,setSelected]=useState('');const assignments=data.assignments;const assignedIds=new Set(assignments.map(a=>a.incidentId));const list=data.incidents.filter(i=>assignedIds.has(i.id)||['ASSIGNED','ACCEPTED','DISPATCHED','ON_SITE','CLEANUP_IN_PROGRESS','CLEANUP_COMPLETED','VERIFICATION'].includes(i.status)).sort((a,b)=>b.actionScore-a.actionScore);const incident=list.find(i=>i.id===selected)
return <div className="min-h-screen bg-canvas"><DemoBar/><header className="sticky top-8 z-30 border-b border-slate-200 bg-white"><div className="mx-auto flex h-16 max-w-2xl items-center justify-between px-4"><Logo/><button onClick={()=>void signOut()} className="grid h-9 w-9 place-items-center rounded-full bg-slate-100 text-slate-600" aria-label="Sign out"><LogOut size={17}/></button></div></header>{incident?<AssignmentDetail incident={incident} back={()=>setSelected('')}/>:<main className="mx-auto max-w-2xl px-4 py-6"><div className="rounded-2xl bg-forest-800 p-5 text-white"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-white/10"><HardHat/></div><div><p className="text-[10px] font-bold uppercase tracking-widest text-forest-100">Field worker</p><h1 className="text-lg font-black">{profile?.fullName}</h1></div></div><div className="mt-5 grid grid-cols-3 divide-x divide-white/15 text-center"><div><b className="text-xl">{list.filter(i=>i.status!=='RESOLVED').length}</b><p className="text-[9px] text-forest-100">Assigned</p></div><div><b className="text-xl">{list.filter(i=>['DISPATCHED','ON_SITE'].includes(i.status)).length}</b><p className="text-[9px] text-forest-100">On route</p></div><div><b className="text-xl">{data.incidents.filter(i=>i.status==='RESOLVED').length}</b><p className="text-[9px] text-forest-100">Done today</p></div></div></div><div className="mt-7 flex items-center justify-between"><div><p className="eyebrow">Live queue</p><h2 className="mt-1 text-xl font-black">My assignments</h2></div><span className="flex items-center gap-1 text-[10px] font-bold text-forest-700"><i className="h-2 w-2 animate-pulse rounded-full bg-emerald-500"/>SYNCED</span></div><div className="mt-4 space-y-3">{list.map(i=>{const team=data.teams.find(t=>t.id===i.assignedTeamId);const vehicle=data.vehicles.find(v=>v.id===i.assignedVehicleId);return <button onClick={()=>setSelected(i.id)} key={i.id} className="card w-full overflow-hidden rounded-2xl text-left"><div className={`h-1 ${i.priorityLevel==='CRITICAL'?'bg-red-600':i.priorityLevel==='HIGH'?'bg-orange-500':'bg-amber-500'}`}/><div className="p-4"><div className="flex items-start justify-between"><div className="flex items-center gap-2"><b>{i.id}</b><PriorityBadge priority={i.priorityLevel}/></div><StatusBadge status={i.status}/></div><div className="mt-3 flex gap-3"><img src={i.mediaUrl} className="h-20 w-20 rounded-xl object-cover"/><div className="min-w-0 flex-1"><h3 className="text-sm font-black">{i.wasteCategory}</h3><p className="mt-1 flex items-center gap-1 truncate text-[11px] text-slate-500"><MapPin size={11}/>{i.address}</p><p className="mt-2 text-[11px] font-bold text-forest-700">{vehicle?.name??i.analysis.response.vehicleType}</p><p className="mt-1 text-[10px] text-slate-500">{team?.name??i.analysis.response.teamType}</p></div><ChevronRight size={17} className="mt-7 text-slate-400"/></div></div></button>})}</div></main>}</div>}

function AssignmentDetail({incident,back}:{incident:Incident;back:()=>void}){const data=useData();const fileRef=useRef<HTMLInputElement>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [verification,setVerification]=useState<CleanupVerification|undefined>(()=>data.verifications.find(v=>v.incidentId===incident.id));const team=data.teams.find(t=>t.id===incident.assignedTeamId);const vehicle=data.vehicles.find(v=>v.id===incident.assignedVehicleId);const action=nextAction[incident.status]
const move=async()=>{if(!action)return;setBusy(true);setError('');try{await data.transitionIncident(incident.id,action.next)}catch(e){setError(e instanceof Error?e.message:'Status could not update.')}finally{setBusy(false)}}
const upload=async(file?:File,defaultUrl?:string)=>{setBusy(true);setError('');try{const url=defaultUrl??(file?await fileToDataUrl(file):'');if(!url)throw new Error('Choose an after-cleanup image.');const result=await data.submitCleanup(incident.id,file?.name??'cleanup-verified.jpg',url);setVerification(result)}catch(e){setError(e instanceof Error?e.message:'Verification failed.')}finally{setBusy(false)}}
const resolve=async()=>{setBusy(true);try{await data.markResolved(incident.id)}catch(e){setError(e instanceof Error?e.message:'Could not resolve.')}finally{setBusy(false)}}
return <main className="mx-auto max-w-2xl pb-10"><div className="relative"><img src={incident.mediaUrl} className="h-64 w-full object-cover"/><button onClick={back} className="absolute left-4 top-4 grid h-10 w-10 place-items-center rounded-full bg-white shadow"><ArrowLeft size={18}/></button><div className="absolute bottom-4 left-4 flex gap-2"><PriorityBadge priority={incident.priorityLevel}/><StatusBadge status={incident.status}/></div><div className="absolute bottom-4 right-4 rounded-lg bg-white px-3 py-2 text-center shadow"><b className="block text-lg">{incident.actionScore}</b><span className="text-[8px] font-bold uppercase text-slate-400">ActionScore</span></div></div><div className="px-4 py-5"><p className="eyebrow">Assignment {incident.id}</p><h1 className="mt-1 text-2xl font-black">{incident.wasteCategory}</h1><p className="mt-2 flex items-start gap-2 text-sm text-slate-500"><MapPin size={16} className="mt-0.5"/>{incident.address}</p><div className="mt-4 grid grid-cols-2 gap-3"><div className="card rounded-xl p-3"><UsersRound size={16} className="text-forest-700"/><p className="label mt-2">Team</p><b className="text-xs">{team?.name??incident.analysis.response.teamType}</b></div><div className="card rounded-xl p-3"><Truck size={16} className="text-forest-700"/><p className="label mt-2">Vehicle</p><b className="text-xs">{vehicle?.name??incident.analysis.response.vehicleType}</b></div></div><a href={`https://www.openstreetmap.org/directions?to=${incident.latitude},${incident.longitude}`} target="_blank" rel="noreferrer"><Button variant="outline" className="mt-3 w-full" icon={<Navigation size={16}/>}>NAVIGATE WITH OPENSTREETMAP</Button></a>
<section className="card mt-5 rounded-2xl p-5"><p className="eyebrow">AI field brief</p><h2 className="mt-2 font-black">{incident.volumeCategory} {incident.wasteCategory.toLowerCase()}</h2>{incident.analysis.hazardFlags.length>0&&<div className="mt-3 flex gap-2 rounded-lg bg-red-50 p-3 text-xs font-bold text-red-700"><AlertTriangle size={16}/>{incident.analysis.hazardFlags[0]}</div>}<p className="mt-4 text-xs leading-5 text-slate-600"><b>Instruction:</b> {incident.analysis.response.reason} Use appropriate PPE and keep bystanders clear.</p></section>
{verification?<section className="mt-5 overflow-hidden rounded-2xl border border-forest-200 bg-white shadow-card"><div className="bg-forest-50 p-5 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-white text-forest-700 shadow"><CheckCircle2 size={28}/></div><p className="eyebrow mt-4">Cleanup {verification.verificationStatus==='VERIFIED'?'verified':'review required'}</p><h2 className="mt-1 text-2xl font-black">{pct(verification.confidence)} confidence</h2><p className="mt-2 text-sm text-slate-600">Remaining waste indicator: <b>{verification.remainingWasteIndicator}</b></p></div><div className="grid grid-cols-2"><div className="relative"><img src={incident.mediaUrl} className="h-32 w-full object-cover"/><span className="absolute bottom-2 left-2 rounded bg-black/70 px-2 py-1 text-[8px] font-bold text-white">BEFORE</span></div><div className="relative"><img src={verification.afterMediaPath} className="h-32 w-full object-cover"/><span className="absolute bottom-2 left-2 rounded bg-forest-700 px-2 py-1 text-[8px] font-bold text-white">AFTER</span></div></div>{verification.verificationStatus==='VERIFIED'&&incident.status==='VERIFICATION'&&<div className="p-4"><Button className="w-full" loading={busy} icon={<ShieldCheck size={16}/>} onClick={()=>void resolve()}>MARK RESOLVED</Button></div>}</section>:incident.status==='CLEANUP_COMPLETED'||incident.status==='VERIFICATION'?<section className="card mt-5 rounded-2xl p-5 text-center"><Camera className="mx-auto text-forest-700" size={28}/><h2 className="mt-3 font-black">Upload after-cleanup evidence</h2><p className="mt-2 text-xs leading-5 text-slate-500">Frame the same area clearly. Dark or blurred evidence will require manual review.</p><input ref={fileRef} type="file" accept="image/*" capture="environment" className="hidden" onChange={e=>void upload(e.target.files?.[0])}/><Button className="mt-4 w-full" loading={busy} icon={<Upload size={16}/>} onClick={()=>fileRef.current?.click()}>UPLOAD AFTER PHOTO</Button><Button className="mt-2 w-full" variant="secondary" disabled={busy} onClick={()=>void upload(undefined,'/demo/cleanup-verified.jpg')}>Run demo verification</Button>{busy&&<p className="mt-4 text-xs font-bold text-forest-700">Verifying cleanup evidence…</p>}</section>:action?<div className="sticky bottom-4 mt-5 rounded-2xl border border-slate-200 bg-white/95 p-4 shadow-lift backdrop-blur"><div className="mb-3 flex items-center justify-between"><div><p className="text-[9px] font-bold uppercase text-slate-400">Current status</p><b className="text-xs">{formatStatus(incident.status)}</b></div><p className="flex items-center gap-1 text-[10px] text-slate-500"><Clock3 size={12}/>{timeAgo(incident.updatedAt)}</p></div><Button className="w-full" size="lg" loading={busy} onClick={()=>void move()}>{action.label}</Button></div>:null}{error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-xs font-semibold text-red-700">{error}</p>}</div></main>}
