import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
import { corsHeaders, json } from '../_shared/cors.ts'
import { score } from '../_shared/decision.ts'
const rad=(v:number)=>v*Math.PI/180
const meters=(a:any,b:any)=>{const p1=rad(a.latitude),p2=rad(b.latitude),dp=rad(b.latitude-a.latitude),dl=rad(b.longitude-a.longitude),h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 6371e3*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});if(req.method!=='POST')return json({error:'Method not allowed'},405);try{
  const auth=req.headers.get('Authorization')??'';const anon=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:auth}}});const {data:{user},error:userError}=await anon.auth.getUser();if(userError||!user)return json({error:'Authentication required'},401)
  const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);const body=await req.json();const analysis=body.analysis;const category=analysis?.categories?.[0]?.category;if(!category||typeof body.latitude!=='number'||typeof body.longitude!=='number')return json({error:'Location and structured analysis are required'},400)
  const since=new Date(Date.now()-72*36e5).toISOString();const {data:nearby}=await admin.from('incidents').select('id,display_id,latitude,longitude,waste_category,captured_at,created_at,report_count,duplicate_master_id').gte('captured_at',since).neq('status','RESOLVED').limit(100)
  const duplicate=(nearby??[]).map((i:any)=>{const d=meters(body,i),same=i.waste_category===category,hours=Math.abs(new Date(body.capturedAt).getTime()-new Date(i.captured_at).getTime())/36e5,base=(d<=150?.42:0)+(hours<=72?.22:0)+(same?.27:0);return{...i,d,probability:Math.min(.96,base+(base>=.75?.07:0))}}).filter((i:any)=>i.probability>=.7).sort((a:any,b:any)=>b.probability-a.probability||b.report_count-a.report_count)[0]
  const masterId=duplicate?.duplicate_master_id??duplicate?.id;let masterContext:any=null;if(masterId){const {data}=await admin.from('incidents').select('report_count,created_at').eq('id',masterId).single();masterContext=data}const ageHours=masterContext?Math.max(0,(Date.now()-new Date(masterContext.created_at).getTime())/36e5):0;const result=score({volume:analysis.volumeCategory,sensitivity:body.sensitivity??'MEDIUM',reportCount:masterContext?masterContext.report_count+1:1,ageHours,hazards:analysis.hazardFlags??[]})
  const {data:incident,error}=await admin.from('incidents').insert({reporter_id:user.id,latitude:body.latitude,longitude:body.longitude,address:body.address,captured_at:body.capturedAt,description:body.description??'',status:'PRIORITIZED',waste_category:category,volume_category:analysis.volumeCategory,action_score:result.score,priority_level:result.priority,location_sensitivity:body.sensitivity??'MEDIUM',sensitivity_reason:body.sensitivityReason,report_count:1,score_factors:result.factors,duplicate_master_id:masterId??null,is_demo:false}).select().single();if(error)throw error;const displayId=incident.display_id
  await Promise.all([
    admin.from('incident_media').insert({incident_id:incident.id,storage_path:body.mediaPath,media_type:body.mediaType==='video'?'video':'image'}),
    admin.from('ai_analyses').insert({incident_id:incident.id,waste_categories:analysis.categories.map((c:any)=>c.category),confidence_scores:Object.fromEntries(analysis.categories.map((c:any)=>[c.category,c.confidence])),volume_category:analysis.volumeCategory,volume_confidence:analysis.volumeConfidence,hazard_flags:analysis.hazardFlags??[],detected_regions:[],recommended_action:analysis.response,model_version:analysis.modelVersion??'prototype',is_prototype:analysis.isPrototype??true}),
    admin.from('incident_status_events').insert([{incident_id:incident.id,from_status:null,to_status:'REPORTED',actor_id:user.id},{incident_id:incident.id,from_status:'REPORTED',to_status:'AI_ANALYZED',actor_id:user.id},{incident_id:incident.id,from_status:'AI_ANALYZED',to_status:'PRIORITIZED',actor_id:user.id}]),
    admin.from('audit_logs').insert({user_id:user.id,action:'INCIDENT_CREATED',entity_type:'incident',entity_id:incident.id,metadata:{duplicate_probability:duplicate?.probability??null}})
  ])
  if(duplicate&&masterId){await admin.from('incidents').update({report_count:(masterContext?.report_count??duplicate.report_count)+1}).eq('id',masterId);const {data:existingCluster}=await admin.from('duplicate_clusters').select('id').eq('master_incident_id',masterId).order('created_at',{ascending:true}).limit(1).maybeSingle();let clusterId=existingCluster?.id;if(!clusterId){const {data:createdCluster}=await admin.from('duplicate_clusters').insert({master_incident_id:masterId,similarity_score:duplicate.probability,detection_reason:[`${Math.round(duplicate.d)}m away`,'Same waste category','Within 72-hour window','Prototype visual-similarity adapter']}).select('id').single();clusterId=createdCluster?.id}if(clusterId)await admin.from('duplicate_cluster_members').upsert([{cluster_id:clusterId,incident_id:masterId,similarity_score:1},{cluster_id:clusterId,incident_id:incident.id,similarity_score:duplicate.probability}],{onConflict:'cluster_id,incident_id'})}
  const {data:officers}=await admin.from('profiles').select('id').in('role',['MUNICIPAL_OFFICER','ADMIN']);if(result.priority==='CRITICAL'&&officers?.length)await admin.from('notifications').insert(officers.map((o:any)=>({user_id:o.id,title:'Critical waste incident detected',message:`${displayId} scored ${result.score}/100 near ${body.sensitivityReason}.`,type:'CRITICAL'})))
  return json({id:incident.id,displayId,actionScore:result.score,duplicate:duplicate?{displayId:duplicate.display_id,probability:duplicate.probability}:null},201)
}catch(e){return json({error:e instanceof Error?e.message:'Submission failed'},400)}})
