import { ArrowRight, Leaf, LogOut, Recycle, Truck } from 'lucide-react'
import { useState } from 'react'
import { DemoBar } from '../../components/DemoBar'
import { DataErrorBanner } from '../../components/DataErrorBanner'
import { Logo } from '../../components/brand/Logo'
import { Badge, PriorityBadge } from '../../components/ui/Badge'
import { IncidentMedia } from '../../components/ui/IncidentMedia'
import { Button } from '../../components/ui/Button'
import { useAuth } from '../../context/AuthContext'
import { useData } from '../../context/DataContext'

export function RecyclingPartner(){const {signOut}=useAuth();const data=useData();const [message,setMessage]=useState('');const recoverable=data.incidents.filter(i=>['Plastic waste','E-waste'].includes(i.wasteCategory)&&i.status!=='RESOLVED');const accept=async(id:string)=>{const team=data.teams.find(t=>t.teamType==='Materials Recovery Team'&&t.availability==='AVAILABLE');const vehicle=data.vehicles.find(v=>v.vehicleType==='Recycling Van'&&v.availability==='AVAILABLE');if(!team||!vehicle){setMessage('No recovery team or recycling van is currently available. Municipal dispatch has been alerted.');return}try{await data.assignIncident(id,team.id,vehicle.id);setMessage(`${id} accepted. The assignment is now visible to the recovery team.`)}catch(e){setMessage(e instanceof Error?e.message:'Could not accept assignment.')}}
return <div className="min-h-screen bg-canvas"><DemoBar/><DataErrorBanner/><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-16 max-w-5xl items-center justify-between px-5"><Logo/><button onClick={()=>void signOut()}><LogOut size={18}/></button></div></header><main className="mx-auto max-w-5xl px-5 py-8"><section className="overflow-hidden rounded-2xl bg-forest-800 p-6 text-white"><Leaf size={27} className="text-[#86d4b1]"/><p className="mt-4 text-[10px] font-bold uppercase tracking-widest text-forest-100">Recovery partner portal</p><h1 className="mt-2 text-3xl font-black">Turn recoverable waste<br/>back into material.</h1><p className="mt-3 max-w-lg text-sm leading-6 text-forest-100">Recyclable-heavy incidents routed through ResponseMatch™. Citizen identity remains hidden.</p></section>{message&&<p role="status" className="mt-5 rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs font-semibold text-blue-800">{message}</p>}<div className="mt-7 flex items-end justify-between"><div><p className="eyebrow">Materials recovery queue</p><h2 className="mt-1 text-xl font-black">Available incidents</h2></div><Badge tone="success">{recoverable.length} signals</Badge></div><div className="mt-4 grid gap-4 md:grid-cols-2">{recoverable.map(i=><article className="card overflow-hidden rounded-2xl" key={i.id}><IncidentMedia url={i.mediaUrl} type={i.mediaType} className="h-44 w-full" alt={`${i.wasteCategory} recovery incident`}/><div className="p-5"><div className="flex items-center justify-between"><b>{i.id}</b><PriorityBadge priority={i.priorityLevel}/></div><h3 className="mt-3 text-lg font-black">{i.wasteCategory} · {i.volumeCategory}</h3><p className="mt-1 text-xs text-slate-500">{i.address}</p><div className="mt-4 flex items-center gap-2 rounded-lg bg-forest-50 p-3 text-xs font-bold text-forest-800"><Recycle size={16}/>Recovery Van + 2 workers</div>{i.status==='PRIORITIZED'?<Button className="mt-4 w-full" icon={<Truck size={16}/>} onClick={()=>void accept(i.id)}>ACCEPT RECYCLING ASSIGNMENT</Button>:<div className="mt-4 flex items-center justify-between rounded-lg border border-slate-200 p-3 text-xs"><span className="font-bold">{i.status.replaceAll('_',' ')}</span><ArrowRight size={14}/></div>}</div></article>)}</div></main></div>}
