import { AlertTriangle, ArrowLeft, BrainCircuit, MapPin, Users } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { PriorityBadge, StatusBadge } from '../../components/ui/Badge'
import { ScoreRing } from '../../components/ui/ScoreRing'
import { IncidentMedia } from '../../components/ui/IncidentMedia'
import { StatusTimeline } from '../../components/ui/Timeline'
import { useData } from '../../context/DataContext'
import { pct } from '../../lib/utils'

export function CitizenIncidentDetail(){const {id}=useParams();const {incidents}=useData();const incident=incidents.find((item)=>item.id===id)
  if(!incident)return <div className="p-6"><Link to="/app/reports" className="text-sm font-bold text-forest-700">← Report not found</Link></div>
  return <div><div className="relative"><IncidentMedia url={incident.mediaUrl} type={incident.mediaType} controls={incident.mediaType==='video'} className="h-64 w-full" alt="Reported waste evidence"/><Link to="/app/reports" className="absolute left-4 top-4 grid h-10 w-10 place-items-center rounded-full bg-white/95 shadow"><ArrowLeft size={18}/></Link><div className="absolute bottom-4 left-4 flex gap-2"><PriorityBadge priority={incident.priorityLevel}/><StatusBadge status={incident.status}/></div></div>
    <div className="px-4 py-6 sm:px-6"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Incident {incident.id}</p><h1 className="mt-1 text-2xl font-black">{incident.wasteCategory}</h1><p className="mt-2 flex items-start gap-1 text-xs leading-5 text-slate-500"><MapPin size={14} className="mt-0.5 shrink-0"/>{incident.address}</p></div><ScoreRing score={incident.actionScore} size="sm"/></div>
      {incident.duplicateMasterId&&<div className="mt-5 flex gap-3 rounded-xl border border-blue-200 bg-blue-50 p-4"><Users className="shrink-0 text-blue-700" size={18}/><div><b className="text-xs text-blue-900">Supporting report linked</b><p className="mt-1 text-xs leading-5 text-blue-700">Matched {incident.duplicateMasterId} at {Math.round((incident.duplicateSimilarity??0)*100)}% prototype similarity. One physical issue → one operational response.</p></div></div>}
      <div className="mt-6 card rounded-2xl p-5"><div className="flex items-center gap-2"><BrainCircuit size={18} className="text-forest-700"/><h2 className="font-black">AI analysis</h2><span className="ml-auto rounded bg-amber-50 px-2 py-1 text-[9px] font-bold text-amber-800">PROTOTYPE</span></div><dl className="mt-4 grid grid-cols-2 gap-4"><div><dt className="label">Waste type</dt><dd className="text-sm font-bold">{incident.wasteCategory}</dd><dd className="text-xs text-slate-500">{pct(incident.analysis.categories[0].confidence)} confidence</dd></div><div><dt className="label">Approx. volume</dt><dd className="text-sm font-bold">{incident.volumeCategory}</dd><dd className="text-xs text-slate-500">{pct(incident.analysis.volumeConfidence)} confidence</dd></div></dl>{incident.analysis.hazardFlags.length>0&&<div className="mt-4 flex gap-2 rounded-lg bg-red-50 p-3 text-xs font-semibold text-red-700"><AlertTriangle size={15}/>{incident.analysis.hazardFlags.join(', ')}</div>}<p className="mt-4 text-[11px] leading-5 text-slate-500">Operational estimate based on visible waste and contextual evidence. Not an exact volume measurement.</p></div>
      <div className="mt-6"><h2 className="font-black">Status timeline</h2><div className="mt-4 card rounded-2xl p-5"><StatusTimeline events={incident.timeline} currentStatus={incident.status}/></div></div>
    </div></div>}
