import { ArrowRight, Camera, CheckCircle2, MapPin, ShieldCheck, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useAuth } from '../../context/AuthContext'
import { useData } from '../../context/DataContext'
import { PriorityBadge, StatusBadge } from '../../components/ui/Badge'
import { timeAgo } from '../../lib/utils'

export function CitizenHome() {
  const { profile } = useAuth(); const { incidents } = useData()
  const mine = incidents.filter((item)=>item.reporterId===profile?.id)
  const resolved = mine.filter((item)=>item.status==='RESOLVED').length
  const recent = mine.slice(0,2)
  return <div className="px-4 py-6 sm:px-6">
    <section className="overflow-hidden rounded-[28px] bg-forest-800 p-6 text-white shadow-lift"><p className="text-sm text-forest-100">Good day, {profile?.fullName.split(' ')[0]}</p><h1 className="mt-2 text-2xl font-black tracking-tight">Make your city cleaner,<br/>one report at a time.</h1><Link to="/app/report" className="mt-7 flex min-h-16 items-center justify-between rounded-2xl bg-white px-5 text-forest-800 shadow-lg active:scale-[.99]"><span className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-forest-100"><Camera size={21}/></span><span><b className="block text-base">REPORT WASTE</b><span className="text-xs font-medium text-slate-500">Photo · Location · AI analysis</span></span></span><ArrowRight size={20}/></Link></section>
    <nav className="mt-4 grid grid-cols-3 gap-2" aria-label="Citizen quick actions"><Link to="/app/reports" className="card rounded-xl p-3 text-center text-[11px] font-bold">My Reports</Link><Link to="/app/nearby" className="card rounded-xl p-3 text-center text-[11px] font-bold">Nearby Issues</Link><Link to="/" className="card rounded-xl p-3 text-center text-[11px] font-bold">How It Works</Link></nav>
    <section className="mt-7"><div className="flex items-end justify-between"><div><p className="eyebrow">Your impact</p><h2 className="mt-1 text-lg font-black">Every report helps</h2></div><span className="rounded-md bg-amber-50 px-2 py-1 text-[9px] font-bold uppercase text-amber-800">Demo statistics</span></div><div className="mt-3 grid grid-cols-3 divide-x divide-slate-200 rounded-2xl border border-slate-200 bg-white py-4 shadow-card"><div className="px-3 text-center"><b className="block text-2xl text-ink">{mine.length || 4}</b><span className="text-[10px] font-semibold text-slate-500">Submitted</span></div><div className="px-3 text-center"><b className="block text-2xl text-forest-700">{resolved || 3}</b><span className="text-[10px] font-semibold text-slate-500">Resolved</span></div><div className="px-3 text-center"><b className="block text-2xl text-ink">{mine.reduce((sum,item)=>sum+item.reportCount,0)||12}</b><span className="text-[10px] font-semibold text-slate-500">Signals added</span></div></div></section>
    <section className="mt-7"><div className="flex items-center justify-between"><h2 className="text-lg font-black">Recent reports</h2><Link className="text-xs font-bold text-forest-700" to="/app/reports">View all</Link></div><div className="mt-3 space-y-3">{(recent.length?recent:incidents.slice(0,2)).map((incident)=><Link to={`/app/reports/${incident.id}`} key={incident.id} className="card flex gap-3 rounded-2xl p-3"><img src={incident.mediaUrl} className="h-20 w-20 rounded-xl object-cover" alt=""/><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><b className="text-xs">{incident.id}</b><StatusBadge status={incident.status}/></div><p className="mt-2 truncate text-sm font-bold">{incident.wasteCategory}</p><p className="mt-1 flex items-center gap-1 truncate text-[11px] text-slate-500"><MapPin size={11}/>{incident.address}</p><div className="mt-1.5 flex items-center justify-between"><PriorityBadge priority={incident.priorityLevel}/><span className="text-[10px] text-slate-400">{timeAgo(incident.createdAt)}</span></div></div></Link>)}</div></section>
    <section className="mt-7 grid gap-3 pb-4 sm:grid-cols-3">{[[Sparkles,'AI-assisted','Waste becomes structured intelligence'],[ShieldCheck,'Privacy first','No public citizen identity'],[CheckCircle2,'Closed loop','Cleanup evidence verified']].map(([Icon,title,copy])=><div className="rounded-xl border border-slate-200 bg-white p-4" key={String(title)}><Icon size={18} className="text-forest-600"/><b className="mt-2 block text-xs">{title as string}</b><p className="mt-1 text-[11px] leading-4 text-slate-500">{copy as string}</p></div>)}</section>
  </div>
}
