import { useMemo, useRef, useState } from 'react'
import { AlertTriangle, ArrowLeft, BrainCircuit, Camera, Check, CheckCircle2, Clock3, FileImage, LocateFixed, MapPin, RotateCcw, ShieldAlert, Sparkles, Truck, Upload } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { Badge } from '../../components/ui/Badge'
import { Button } from '../../components/ui/Button'
import { ScoreRing } from '../../components/ui/ScoreRing'
import { IncidentMedia } from '../../components/ui/IncidentMedia'
import { useAuth } from '../../context/AuthContext'
import { useData } from '../../context/DataContext'
import { calculateActionScore } from '../../services/decisionEngine'
import { createWasteAnalyzer } from '../../services/aiService'
import { detectDuplicate } from '../../services/duplicateService'
import { mediaFileToDataUrl, pct, publicAsset } from '../../lib/utils'
import type { AIAnalysis, SensitivityLevel, WasteCategory } from '../../types/domain'

type Step = 'capture' | 'analyzing' | 'review' | 'submitting' | 'done'
interface Scenario { title: string; category: WasteCategory; image: string; description: string; sensitivity: SensitivityLevel; reason: string }
const scenarios: Scenario[] = [
  { title: 'Overflowing bin', category: 'Overflowing bin', image: publicAsset('/demo/overflowing-bin.jpg'), description: 'Medium overflowing bin beside residential walkway', sensitivity: 'MEDIUM', reason: 'Residential zone' },
  { title: 'Critical debris', category: 'Construction debris', image: publicAsset('/demo/construction-debris.jpg'), description: 'Large construction debris blocking drain near school', sensitivity: 'HIGH', reason: 'Fictional Shantivan School (86m)' },
  { title: 'Hazardous waste', category: 'Hazardous waste', image: publicAsset('/demo/hazardous-waste.jpg'), description: 'Leaking chemical containers require urgent response', sensitivity: 'MEDIUM', reason: 'Service road' },
]
const progressLabels = ['Image received','Detecting waste','Estimating visible volume','Checking hazards','Checking nearby reports','Calculating response priority']

export function ReportFlow() {
  const { profile } = useAuth(); const data=useData(); const navigate=useNavigate(); const analyzer=useMemo(()=>createWasteAnalyzer(),[])
  const fileRef=useRef<HTMLInputElement>(null); const cameraRef=useRef<HTMLInputElement>(null)
  const [step,setStep]=useState<Step>('capture'); const [preview,setPreview]=useState(''); const [mediaType,setMediaType]=useState<'image'|'video'>('image'); const [fileName,setFileName]=useState(''); const [description,setDescription]=useState('')
  const [scenario,setScenario]=useState<Scenario|null>(null); const [analysis,setAnalysis]=useState<AIAnalysis|null>(null); const [progress,setProgress]=useState(0); const [error,setError]=useState('')
  const [location,setLocation]=useState({latitude:12.9716,longitude:77.5946,address:'Demo City · Location pending',source:'fallback' as 'gps'|'fallback'})
  const [capturedAt]=useState(new Date().toISOString()); const [submittedId,setSubmittedId]=useState('')

  const requestLocation=()=>{setError('');if(!navigator.geolocation){setError('Location is not supported in this browser. You can continue with the clearly labelled demo location.');return}navigator.geolocation.getCurrentPosition((pos)=>setLocation({latitude:pos.coords.latitude,longitude:pos.coords.longitude,address:`GPS ${pos.coords.latitude.toFixed(5)}, ${pos.coords.longitude.toFixed(5)}`,source:'gps'}),()=>setError('Location permission was denied. You may continue with the labelled approximate demo location or enable location in browser settings.'),{enableHighAccuracy:true,timeout:8000})}
  const selectScenario=(item:Scenario)=>{setScenario(item);setPreview(item.image);setMediaType('image');setFileName(`${item.category.toLowerCase().replaceAll(' ','-')}.jpg`);setDescription(item.description);setError('')}
  const chooseFile=async(file?:File)=>{if(!file)return;try{setError('');setPreview(await mediaFileToDataUrl(file));setMediaType(file.type.startsWith('video/')?'video':'image');setFileName(file.name);setScenario(null)}catch(err){setError(err instanceof Error?err.message:'Invalid report media.')}}
  const analyze=async()=>{if(!preview){setError('Take or upload a photo or short video before starting analysis.');return}setStep('analyzing');setError('');setProgress(0);const timer=window.setInterval(()=>setProgress((value)=>Math.min(progressLabels.length-1,value+1)),380);try{const result=await Promise.all([analyzer.analyze({fileName,description,scenarioHint:scenario?.category,sensitivity:scenario?.sensitivity??'MEDIUM'}),new Promise(r=>setTimeout(r,2300))]);setAnalysis(result[0]);setProgress(progressLabels.length);setTimeout(()=>setStep('review'),300)}catch(err){setError(err instanceof Error?err.message:'AI analysis failed. You can retry without losing the report.');setStep('capture')}finally{clearInterval(timer)}}
  const sensitivity=scenario?.sensitivity??'MEDIUM'; const sensitivityReason=scenario?.reason??'Residential zone'
  const duplicate=analysis?detectDuplicate({latitude:location.latitude,longitude:location.longitude,category:analysis.categories[0].category,capturedAt},data.incidents):null
  const duplicateMaster=duplicate?data.incidents.find((item)=>item.id===duplicate.matchingIncidentId):null
  const score=analysis?calculateActionScore({
    volume:analysis.volumeCategory,
    sensitivity,
    reportCount:duplicateMaster?duplicateMaster.reportCount+1:1,
    ageHours:duplicateMaster?Math.max(0,(Date.now()-new Date(duplicateMaster.createdAt).getTime())/36e5):0,
    hazards:analysis.hazardFlags,
  }):null
  const submit=async()=>{if(!analysis||!profile)return;setStep('submitting');try{const incident=await data.createIncident({reporterId:profile.id,latitude:location.latitude,longitude:location.longitude,address:location.address,description,mediaUrl:preview,mediaType,capturedAt,analysis,sensitivity,sensitivityReason});setSubmittedId(incident.id);setStep('done')}catch(err){setError(err instanceof Error?err.message:'Report could not be submitted.');setStep('review')}}

  if(step==='analyzing')return <div className="min-h-[calc(100vh-7rem)] bg-forest-900 px-5 py-10 text-white"><div className="mx-auto max-w-md"><div className="text-center"><div className="relative mx-auto h-52 overflow-hidden rounded-2xl border border-white/15"><IncidentMedia url={preview} type={mediaType} className="h-full w-full opacity-70" alt="Waste media being analyzed"/><div className="scan-line absolute inset-x-0 top-2 h-0.5 bg-[#86d4b1] shadow-[0_0_14px_#86d4b1]"/><div className="absolute inset-0 grid place-items-center"><BrainCircuit className="text-white drop-shadow" size={40}/></div></div><p className="mt-7 text-xs font-extrabold uppercase tracking-[.18em] text-forest-100">Analyzing report</p><h1 className="mt-2 text-2xl font-black">Turning media into a decision</h1><p className="mt-2 text-xs text-forest-100">Prototype analyzer · Approximate operational estimates</p></div><div className="mt-8 space-y-3">{progressLabels.map((label,index)=><div className={`flex items-center gap-3 rounded-xl border px-4 py-3 transition ${index<=progress?'border-forest-500 bg-forest-800':'border-white/10 text-white/35'}`} key={label}><span className={`grid h-6 w-6 place-items-center rounded-full ${index<progress?'bg-[#86d4b1] text-forest-900':index===progress?'border-2 border-[#86d4b1]':'border border-white/20'}`}>{index<progress?<Check size={13} strokeWidth={3}/>:index===progress?<span className="h-2 w-2 animate-pulse rounded-full bg-[#86d4b1]"/>:null}</span><span className="text-sm font-semibold">{label}</span></div>)}</div></div></div>

  if(step==='done')return <div className="grid min-h-[calc(100vh-9rem)] place-items-center px-5 py-10"><div className="w-full max-w-sm text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-forest-100 text-forest-700"><CheckCircle2 size={38}/></div><p className="eyebrow mt-6">Report received</p><h1 className="mt-2 text-3xl font-black">{submittedId}</h1><p className="mt-3 text-sm leading-6 text-slate-600">Authorities have received your structured report.</p><div className="card mt-6 rounded-2xl p-5 text-left"><div className="flex items-center justify-between border-b border-slate-100 pb-3"><span className="text-xs font-bold text-slate-500">Status</span><Badge tone="info">AI VERIFIED</Badge></div><div className="flex items-center justify-between pt-3"><span className="text-xs font-bold text-slate-500">ActionScore</span><span className="text-lg font-black">{score?.score} / 100</span></div></div><Button className="mt-6 w-full" size="lg" onClick={()=>navigate(`/app/reports/${submittedId}`)}>TRACK REPORT</Button><Button className="mt-2 w-full" variant="ghost" onClick={()=>navigate('/app')}>Back to home</Button></div></div>

  if((step==='review'||step==='submitting')&&analysis&&score)return <div className="px-4 py-5 sm:px-6"><button onClick={()=>setStep('capture')} className="flex items-center gap-2 text-xs font-bold text-slate-600"><ArrowLeft size={16}/> Edit report</button><div className="mt-5 flex items-center justify-between"><div><p className="eyebrow">Report summary</p><h1 className="mt-1 text-2xl font-black">Review intelligence</h1></div><span className="rounded bg-amber-50 px-2 py-1 text-[9px] font-bold text-amber-800">DEMO AI</span></div>
    <div className="relative mt-5 overflow-hidden rounded-2xl"><IncidentMedia url={preview} type={mediaType} controls={mediaType==='video'} className="h-56 w-full" alt="Waste report evidence"/><div className="absolute bottom-3 left-3 rounded-lg bg-black/70 px-3 py-1.5 text-[10px] font-bold text-white">Captured {new Date(capturedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</div></div>
    <section className="card mt-4 rounded-2xl p-5"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Sparkles size={17} className="text-forest-700"/><h2 className="font-black">AI analysis</h2></div><h3 className="mt-4 text-xl font-black">{analysis.categories[0].category}</h3><p className="text-sm font-semibold text-forest-700">{pct(analysis.categories[0].confidence)} confidence</p></div><div className="rounded-xl bg-slate-50 px-4 py-3 text-center"><span className="label">Approx. volume</span><b className="text-sm">{analysis.volumeCategory.toUpperCase()}</b><span className="block text-[10px] text-slate-500">{pct(analysis.volumeConfidence)}</span></div></div>{analysis.hazardFlags.length>0?<div className="mt-4 flex gap-2 rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700"><ShieldAlert size={18}/><div><span className="text-[9px] uppercase tracking-widest">Potential hazard</span><p className="mt-0.5">{analysis.hazardFlags.join(', ')}</p></div></div>:<div className="mt-4 flex gap-2 rounded-xl bg-forest-50 p-3 text-xs font-semibold text-forest-700"><CheckCircle2 size={16}/>No contextual hazard signal detected</div>}<p className="mt-4 text-[11px] leading-5 text-slate-500">Operational estimate based on visible waste and contextual evidence. This is not an exact cubic-volume measurement.</p></section>
    {duplicate&&<section className="mt-4 rounded-2xl border border-blue-200 bg-blue-50 p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-widest text-blue-700">Possible duplicate</p><h2 className="mt-1 text-lg font-black text-blue-950">{Math.round(duplicate.probability*100)}% similarity</h2></div><RotateCcw className="text-blue-700"/></div><div className="mt-3 space-y-1.5">{duplicate.reasons.map(r=><p className="flex items-center gap-2 text-xs text-blue-800" key={r}><Check size={12}/>{r}</p>)}</div><p className="mt-3 text-xs font-bold text-blue-900">Will support master incident {duplicate.matchingIncidentId}</p></section>}
    <section className="mt-4 grid grid-cols-[auto_1fr] items-center gap-4 rounded-2xl bg-forest-800 p-5 text-white"><ScoreRing score={score.score} size="md"/><div><p className="text-[10px] font-bold uppercase tracking-widest text-forest-100">Initial ActionScore™</p><h2 className="mt-1 text-lg font-black">{score.priority} priority</h2><p className="mt-1 text-xs leading-5 text-forest-100">Explainable score updates as reports and incident age change.</p></div></section>
    <section className="card mt-4 rounded-2xl p-5"><div className="flex gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-forest-100 text-forest-700"><Truck size={20}/></div><div><p className="eyebrow">ResponseMatch™</p><h2 className="mt-1 font-black">{analysis.response.vehicleType} + {analysis.response.workerCount} workers</h2><p className="mt-2 text-xs leading-5 text-slate-600">{analysis.response.reason}</p>{analysis.response.escalation!=='NONE'&&<Badge tone={analysis.response.escalation==='IMMEDIATE'?'critical':'high'} className="mt-3">{analysis.response.escalation.replace('_',' ')} escalation</Badge>}</div></div></section>
    <div className="mt-4 card rounded-2xl p-4"><div className="flex gap-3 text-xs"><MapPin size={16} className="shrink-0 text-forest-700"/><div><b>{location.address}</b><p className="mt-1 text-slate-500">{location.source==='gps'?'GPS captured with permission':'Approximate demo location — GPS not provided'}</p></div></div><div className="mt-3 flex gap-3 text-xs"><Clock3 size={16} className="text-forest-700"/><b>{new Date(capturedAt).toLocaleString()}</b></div></div>
    {error&&<p role="alert" className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-xs font-semibold text-red-700">{error}</p>}<Button className="mt-5 w-full" size="lg" loading={step==='submitting'} onClick={()=>void submit()}>SUBMIT REPORT</Button><p className="mt-3 text-center text-[10px] leading-4 text-slate-500">By submitting, you consent to using this media and location for incident response. Citizen identity is not public.</p>
  </div>

  return <div className="px-4 py-5 sm:px-6"><div className="flex items-center gap-3"><Link to="/app" className="grid h-10 w-10 place-items-center rounded-full border border-slate-200 bg-white"><ArrowLeft size={18}/></Link><div><p className="eyebrow">Step 1 of 3</p><h1 className="text-xl font-black">Capture waste</h1></div></div>
    <div className="mt-5 overflow-hidden rounded-[24px] border-2 border-dashed border-slate-300 bg-slate-100">{preview?<div className="relative"><IncidentMedia url={preview} type={mediaType} controls={mediaType==='video'} className="h-72 w-full" alt="Selected waste evidence"/><button onClick={()=>{setPreview('');setScenario(null)}} className="absolute right-3 top-3 rounded-lg bg-black/65 px-3 py-2 text-xs font-bold text-white">Change</button></div>:<div className="grid h-72 place-items-center p-6 text-center"><div><div className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-white text-forest-700 shadow-card"><Camera size={34}/></div><h2 className="mt-4 font-black">Capture clear waste evidence</h2><p className="mt-2 text-xs leading-5 text-slate-500">Keep the waste and nearby context visible.<br/>Avoid identifiable faces.</p></div></div>}</div>
    <input ref={cameraRef} type="file" accept="image/*,video/mp4,video/webm" capture="environment" className="hidden" onChange={(e)=>void chooseFile(e.target.files?.[0])}/><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" className="hidden" onChange={(e)=>void chooseFile(e.target.files?.[0])}/>
    <div className="mt-3 grid grid-cols-2 gap-3"><Button variant="primary" size="lg" icon={<Camera size={19}/>} onClick={()=>cameraRef.current?.click()}>Photo / video</Button><Button variant="outline" size="lg" icon={<Upload size={19}/>} onClick={()=>fileRef.current?.click()}>Upload</Button></div>
    <div className="mt-6"><div className="flex items-center justify-between"><label className="label" htmlFor="comment">Optional comment</label><span className="text-[10px] text-slate-400">{description.length}/280</span></div><textarea id="comment" className="input min-h-24 resize-none" maxLength={280} value={description} onChange={e=>setDescription(e.target.value)} placeholder="What can you see? Mention drains, smoke, sharp objects or nearby schools…"/></div>
    <div className="mt-5 rounded-2xl border border-slate-200 bg-white p-4"><div className="flex gap-3"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-full ${location.source==='gps'?'bg-forest-100 text-forest-700':'bg-amber-50 text-amber-700'}`}><LocateFixed size={19}/></span><div className="min-w-0 flex-1"><b className="text-sm">{location.source==='gps'?'Location captured':'Location permission'}</b><p className="mt-1 truncate text-xs text-slate-500">{location.address}</p></div><Button size="sm" variant="ghost" onClick={requestLocation}>{location.source==='gps'?'Refresh':'Allow'}</Button></div></div>
    <div className="mt-6"><div className="flex items-center gap-2"><FileImage size={16} className="text-forest-700"/><h2 className="text-sm font-black">Or load a reproducible demo</h2></div><div className="hide-scrollbar -mx-4 mt-3 flex gap-3 overflow-x-auto px-4 pb-2">{scenarios.map(item=><button key={item.title} onClick={()=>selectScenario(item)} className={`w-36 shrink-0 overflow-hidden rounded-xl border bg-white text-left ${scenario?.title===item.title?'border-forest-600 ring-2 ring-forest-100':'border-slate-200'}`}><img src={item.image} className="h-20 w-full object-cover" alt=""/><span className="block p-2 text-xs font-bold">{item.title}</span></button>)}</div></div>
    {error&&<div role="alert" className="mt-4 flex gap-2 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-900"><AlertTriangle size={16} className="shrink-0"/>{error}</div>}
    <Button className="mt-6 w-full" size="lg" icon={<BrainCircuit size={19}/>} onClick={()=>void analyze()}>ANALYZE REPORT</Button><p className="mt-3 text-center text-[10px] text-slate-500">AI-assisted prototype result · You review before submission</p>
  </div>
}
