import { Database, FileClock, LogOut, RotateCcw, ShieldCheck, Truck, UsersRound } from 'lucide-react'
import { DemoBar } from '../../components/DemoBar'
import { Logo } from '../../components/brand/Logo'
import { Badge } from '../../components/ui/Badge'
import { Button } from '../../components/ui/Button'
import { useAuth } from '../../context/AuthContext'
import { useData } from '../../context/DataContext'
import { shortDate } from '../../lib/utils'

export function AdminConsole(){const {signOut}=useAuth();const data=useData();return <div className="min-h-screen bg-canvas"><DemoBar/><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-5"><Logo/><button onClick={()=>void signOut()}><LogOut size={18}/></button></div></header><main className="mx-auto max-w-6xl px-5 py-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Administration</p><h1 className="mt-2 text-3xl font-black">System controls</h1><p className="mt-2 text-sm text-slate-500">Resources, role boundaries and an immutable operational audit trail.</p></div><Button variant="outline" icon={<RotateCcw size={15}/>} onClick={()=>void data.resetDemo()}>Reset prototype data</Button></div><section className="mt-7 grid gap-4 sm:grid-cols-3">{[
  { Icon: UsersRound, value: data.teams.length, label: 'Response teams' },
  { Icon: Truck, value: data.vehicles.length, label: 'Municipal vehicles' },
  { Icon: Database, value: data.incidents.length, label: 'Incident records' },
].map(({Icon,value,label})=><div className="card rounded-2xl p-5" key={label}><Icon className="text-forest-700"/><b className="mt-4 block text-3xl">{value}</b><span className="text-xs text-slate-500">{label}</span></div>)}</section><div className="mt-6 grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><section className="card rounded-2xl p-5"><ShieldCheck className="text-forest-700"/><h2 className="mt-3 font-black">Role enforcement</h2><p className="mt-2 text-xs leading-5 text-slate-500">Frontend route guards improve navigation; Supabase Row Level Security remains the authorization boundary.</p><div className="mt-5 space-y-2">{['CITIZEN','FIELD_WORKER','MUNICIPAL_OFFICER','ADMIN','RECYCLING_PARTNER'].map(role=><div className="flex items-center justify-between rounded-lg bg-slate-50 p-3" key={role}><span className="text-[10px] font-bold">{role}</span><Badge tone="success">POLICY ACTIVE</Badge></div>)}</div></section><section className="card overflow-hidden rounded-2xl"><div className="flex items-center gap-2 border-b border-slate-100 p-5"><FileClock className="text-forest-700"/><div><p className="eyebrow">Audit trail</p><h2 className="mt-1 font-black">Recent operational actions</h2></div></div>{data.auditLogs.length?<div className="divide-y divide-slate-100">{[...data.auditLogs].reverse().slice(0,12).map(log=><div className="grid grid-cols-[1fr_auto] gap-3 p-4" key={log.id}><div><b className="text-xs">{log.action.replaceAll('_',' ')}</b><p className="mt-1 text-[10px] text-slate-500">{log.entityType} · {log.entityId} · actor {log.userId}</p></div><time className="text-[10px] text-slate-400">{shortDate(log.createdAt)}</time></div>)}</div>:<div className="grid min-h-64 place-items-center p-8 text-center"><div><FileClock className="mx-auto text-slate-300" size={30}/><p className="mt-3 text-sm font-bold">No session actions yet</p><p className="mt-1 text-xs text-slate-500">Assignments and status transitions appear here.</p></div></div>}</section></div></main></div>}
