import { useState } from 'react'
import { Database, FileClock, LogOut, RotateCcw, ShieldCheck, Tags, Truck, UsersRound } from 'lucide-react'
import { DemoBar } from '../../components/DemoBar'
import { DataErrorBanner } from '../../components/DataErrorBanner'
import { Logo } from '../../components/brand/Logo'
import { Badge } from '../../components/ui/Badge'
import { Button } from '../../components/ui/Button'
import { useAuth } from '../../context/AuthContext'
import { useData } from '../../context/DataContext'
import { shortDate } from '../../lib/utils'
import type { Role } from '../../types/domain'

export function AdminConsole(){
  const {profile,signOut}=useAuth();const data=useData();const [notice,setNotice]=useState('')
  const run=async(action:()=>Promise<void>,success:string)=>{setNotice('');try{await action();setNotice(success)}catch(error){setNotice(error instanceof Error?error.message:'Administrative change failed.')}}
  return <div className="min-h-screen bg-canvas"><DemoBar/><DataErrorBanner/><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-5"><Logo/><button onClick={()=>void signOut()} className="grid h-9 w-9 place-items-center rounded-lg border border-slate-200" aria-label="Sign out"><LogOut size={18}/></button></div></header>
  <main className="mx-auto max-w-6xl px-5 py-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Administration</p><h1 className="mt-2 text-3xl font-black">System controls</h1><p className="mt-2 text-sm text-slate-500">Resources, category governance, role boundaries and an operational audit trail.</p></div><Button variant="outline" icon={<RotateCcw size={15}/>} onClick={()=>void data.resetDemo()}>Reset prototype data</Button></div>
  {notice&&<p role="status" className="mt-5 rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs font-semibold text-blue-800">{notice}</p>}
  <section className="mt-7 grid gap-4 sm:grid-cols-3">{[
    { Icon: UsersRound, value: data.teams.length, label: 'Response teams' },
    { Icon: Truck, value: data.vehicles.length, label: 'Municipal vehicles' },
    { Icon: Database, value: data.incidents.length, label: 'Incident records' },
  ].map(({Icon,value,label})=><div className="card rounded-2xl p-5" key={label}><Icon className="text-forest-700"/><b className="mt-4 block text-3xl">{value}</b><span className="text-xs text-slate-500">{label}</span></div>)}</section>

  <section className="card mt-6 rounded-2xl p-5"><div className="flex items-center gap-3"><UsersRound className="text-forest-700"/><div><p className="eyebrow">Identity governance</p><h2 className="mt-1 font-black">Users and roles</h2></div><Badge tone="info" className="ml-auto">{data.profiles.length} users</Badge></div><p className="mt-3 text-xs leading-5 text-slate-500">Role changes are database-authorized and audited. Your current administrator role is locked during this session.</p><div className="mt-5 grid gap-3 md:grid-cols-2">{data.profiles.map(user=><div className="flex items-center gap-3 rounded-xl border border-slate-200 p-3" key={user.id}><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-forest-50 text-xs font-black text-forest-700">{user.fullName.slice(0,2).toUpperCase()}</span><div className="min-w-0 flex-1"><b className="block truncate text-xs">{user.fullName}</b><p className="truncate text-[10px] text-slate-500">{user.email}</p></div><select disabled={user.id===profile?.id} aria-label={`${user.fullName} role`} value={user.role} onChange={event=>void run(()=>data.updateUserRole(user.id,event.target.value as Role),`${user.fullName}'s role updated.`)} className="max-w-36 rounded-lg border border-slate-300 bg-white px-2 py-2 text-[9px] font-bold disabled:bg-slate-100"><option>CITIZEN</option><option>FIELD_WORKER</option><option>MUNICIPAL_OFFICER</option><option>ADMIN</option><option>RECYCLING_PARTNER</option></select></div>)}</div></section>

  <section className="card mt-6 rounded-2xl p-5"><div className="flex items-center gap-3"><Tags className="text-forest-700"/><div><p className="eyebrow">Category governance</p><h2 className="mt-1 font-black">Waste categories</h2></div><Badge tone="info" className="ml-auto">{data.categories.filter(item=>item.active).length} active</Badge></div><p className="mt-3 text-xs leading-5 text-slate-500">Disabled categories remain available on historical incidents. Changes are persisted and added to the audit trail.</p><div className="mt-5 grid gap-3 md:grid-cols-2">{data.categories.map(category=><div className="flex items-center gap-3 rounded-xl border border-slate-200 p-3" key={category.id}><div className="min-w-0 flex-1"><b className="text-xs">{category.name}</b><p className="mt-1 truncate text-[10px] text-slate-500">{category.handlingNotes}</p></div><button aria-pressed={category.active} onClick={()=>void run(()=>data.updateCategoryActive(category.id,!category.active),`${category.name} ${category.active?'disabled':'enabled'}.`)} className={`relative h-7 w-12 rounded-full transition ${category.active?'bg-forest-600':'bg-slate-300'}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow transition ${category.active?'left-6':'left-1'}`}/><span className="sr-only">{category.active?'Disable':'Enable'} {category.name}</span></button></div>)}</div></section>

  <div className="mt-6 grid gap-6 lg:grid-cols-2"><ResourceControl title="Team availability" icon={<UsersRound/>}>{data.teams.map(team=><div className="flex items-center gap-3 border-b border-slate-100 py-3 last:border-0" key={team.id}><div className="min-w-0 flex-1"><b className="block truncate text-xs">{team.name}</b><span className="text-[10px] text-slate-500">{team.teamType} · {team.workerCount} workers</span></div><select aria-label={`${team.name} availability`} value={team.availability} onChange={event=>void run(()=>data.updateTeamAvailability(team.id,event.target.value as 'AVAILABLE'|'ASSIGNED'|'OFF_DUTY'),`${team.name} availability updated.`)} className="rounded-lg border border-slate-300 bg-white px-2 py-2 text-[10px] font-bold"><option>AVAILABLE</option><option>ASSIGNED</option><option>OFF_DUTY</option></select></div>)}</ResourceControl>
  <ResourceControl title="Vehicle availability" icon={<Truck/>}>{data.vehicles.map(vehicle=><div className="flex items-center gap-3 border-b border-slate-100 py-3 last:border-0" key={vehicle.id}><div className="min-w-0 flex-1"><b className="block truncate text-xs">{vehicle.name}</b><span className="text-[10px] text-slate-500">{vehicle.vehicleType} · {vehicle.capacity}</span></div><select aria-label={`${vehicle.name} availability`} value={vehicle.availability} onChange={event=>void run(()=>data.updateVehicleAvailability(vehicle.id,event.target.value as 'AVAILABLE'|'ASSIGNED'|'MAINTENANCE'),`${vehicle.name} availability updated.`)} className="rounded-lg border border-slate-300 bg-white px-2 py-2 text-[10px] font-bold"><option>AVAILABLE</option><option>ASSIGNED</option><option>MAINTENANCE</option></select></div>)}</ResourceControl></div>

  <div className="mt-6 grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><section className="card rounded-2xl p-5"><ShieldCheck className="text-forest-700"/><h2 className="mt-3 font-black">Role enforcement</h2><p className="mt-2 text-xs leading-5 text-slate-500">Frontend route guards improve navigation; Supabase Row Level Security remains the authorization boundary.</p><div className="mt-5 space-y-2">{['CITIZEN','FIELD_WORKER','MUNICIPAL_OFFICER','ADMIN','RECYCLING_PARTNER'].map(role=><div className="flex items-center justify-between rounded-lg bg-slate-50 p-3" key={role}><span className="text-[10px] font-bold">{role}</span><Badge tone="success">POLICY ACTIVE</Badge></div>)}</div></section>
  <section className="card overflow-hidden rounded-2xl"><div className="flex items-center gap-2 border-b border-slate-100 p-5"><FileClock className="text-forest-700"/><div><p className="eyebrow">Audit trail</p><h2 className="mt-1 font-black">Recent operational actions</h2></div></div>{data.auditLogs.length?<div className="max-h-[460px] divide-y divide-slate-100 overflow-y-auto">{[...data.auditLogs].reverse().slice(0,20).map(log=><div className="grid grid-cols-[1fr_auto] gap-3 p-4" key={log.id}><div><b className="text-xs">{log.action.replaceAll('_',' ')}</b><p className="mt-1 text-[10px] text-slate-500">{log.entityType} · {log.entityId} · actor {log.userId}</p></div><time className="text-[10px] text-slate-400">{shortDate(log.createdAt)}</time></div>)}</div>:<div className="grid min-h-64 place-items-center p-8 text-center"><div><FileClock className="mx-auto text-slate-300" size={30}/><p className="mt-3 text-sm font-bold">No session actions yet</p><p className="mt-1 text-xs text-slate-500">Assignments and administrative changes appear here.</p></div></div>}</section></div></main></div>}

function ResourceControl({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="card rounded-2xl p-5"><div className="flex items-center gap-2 text-forest-700">{icon}<h2 className="font-black text-ink">{title}</h2></div><div className="mt-3">{children}</div></section>}
