import 'leaflet/dist/leaflet.css'
import L from 'leaflet'
import { useMemo, useState } from 'react'
import { Circle, MapContainer, Marker, Popup, TileLayer } from 'react-leaflet'
import { ArrowRight, Filter, Layers3, MapPin } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PriorityBadge, StatusBadge } from '../../components/ui/Badge'
import { useData } from '../../context/DataContext'

const colors:Record<string,string>={CRITICAL:'#c93235',HIGH:'#dd6b20',MEDIUM:'#b7791f',LOW:'#23815d',RESOLVED:'#64748b'}
const markerIcon=(score:number,priority:string,status:string)=>L.divIcon({className:'',html:`<div class="custom-map-marker" style="background:${colors[status==='RESOLVED'?'RESOLVED':priority]}"><span>${score}</span></div>`,iconSize:[28,28],iconAnchor:[14,28],popupAnchor:[0,-27]})

export function CityMap(){const {incidents,hotspots}=useData();const [priority,setPriority]=useState('ALL');const [status,setStatus]=useState('ACTIVE');const [showHotspots,setShowHotspots]=useState(true);const shown=useMemo(()=>incidents.filter(i=>priority==='ALL'||i.priorityLevel===priority).filter(i=>status==='ALL'||(status==='ACTIVE'?i.status!=='RESOLVED':i.status==='RESOLVED')),[incidents,priority,status])
return <div className="flex h-[calc(100vh-6rem)] min-h-[620px] flex-col"><div className="border-b border-slate-200 bg-white px-4 py-4 sm:px-6 lg:px-8"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="eyebrow">Geospatial operations</p><h1 className="mt-1 text-2xl font-black">City intelligence map</h1></div><div className="flex flex-wrap gap-2"><label className="relative"><Filter size={13} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><select className="input py-2 pl-8 text-xs" value={priority} onChange={e=>setPriority(e.target.value)} aria-label="Priority filter"><option value="ALL">All priorities</option><option>CRITICAL</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select></label><select className="input w-auto py-2 text-xs" value={status} onChange={e=>setStatus(e.target.value)} aria-label="Status filter"><option value="ACTIVE">Active</option><option value="RESOLVED">Resolved</option><option value="ALL">All status</option></select><button onClick={()=>setShowHotspots(v=>!v)} className={`flex items-center gap-2 rounded-xl border px-3 text-xs font-bold ${showHotspots?'border-forest-300 bg-forest-50 text-forest-800':'border-slate-300 bg-white text-slate-500'}`}><Layers3 size={14}/>Hotspots</button></div></div></div>
<div className="relative flex-1"><MapContainer center={[12.9716,77.5946]} zoom={14} scrollWheelZoom className="z-0"><TileLayer attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{showHotspots&&hotspots.map(h=><Circle key={h.id} center={[h.centerLatitude,h.centerLongitude]} radius={260} pathOptions={{color:'#dd6b20',fillColor:'#f6ad55',fillOpacity:.17,weight:2,dashArray:'5 5'}}/>)}{shown.map(i=><Marker key={i.id} position={[i.latitude,i.longitude]} icon={markerIcon(i.actionScore,i.priorityLevel,i.status)}><Popup minWidth={250}><div className="p-1 font-sans"><div className="flex items-center justify-between"><b className="text-sm">{i.id}</b><PriorityBadge priority={i.priorityLevel}/></div><h2 className="mt-3 text-sm font-black">{i.wasteCategory} · {i.volumeCategory}</h2><p className="mt-1 flex items-start gap-1 text-[11px] leading-4 text-slate-500"><MapPin size={11}/>{i.address}</p><div className="mt-3 flex items-center justify-between rounded-lg bg-slate-50 p-2"><span className="text-[10px] font-bold text-slate-500">ActionScore</span><b className="text-lg">{i.actionScore}/100</b></div><div className="mt-2"><StatusBadge status={i.status}/></div><p className="mt-3 text-[10px] text-slate-500"><b>Response:</b> {i.analysis.response.vehicleType} + {i.analysis.response.workerCount} workers</p><Link to={`/command/incidents/${i.id}`} className="mt-3 flex items-center justify-center gap-1 rounded-lg bg-forest-700 py-2 text-xs font-bold text-white">Open incident <ArrowRight size={12}/></Link></div></Popup></Marker>)}</MapContainer><div className="absolute bottom-5 left-5 z-[400] hidden rounded-xl border border-slate-200 bg-white p-3 shadow-lift sm:block"><p className="text-[9px] font-extrabold uppercase tracking-widest text-slate-400">Map legend · ActionScore marker</p><div className="mt-2 flex gap-3">{Object.entries(colors).map(([k,c])=><span className="flex items-center gap-1 text-[9px] font-bold" key={k}><i className="h-2.5 w-2.5 rounded-full" style={{background:c}}/>{k}</span>)}</div></div><div className="absolute right-3 top-3 z-[400] rounded-lg bg-white px-3 py-2 text-[10px] font-bold shadow">{shown.length} incidents shown</div></div></div>}
