import { useState } from 'react'
import { AlertTriangle, ArrowLeft, BrainCircuit, Check, Clock3, MapPin, Network, ShieldAlert, Sparkles, Truck, UserCheck, UsersRound } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { Badge, PriorityBadge, StatusBadge } from '../../components/ui/Badge'
import { Button } from '../../components/ui/Button'
import { ScoreRing } from '../../components/ui/ScoreRing'
import { IncidentMedia } from '../../components/ui/IncidentMedia'
import { StatusTimeline } from '../../components/ui/Timeline'
import { useData } from '../../context/DataContext'
import { explainScore } from '../../services/decisionEngine'
import { pct, shortDate, timeAgo } from '../../lib/utils'

export function IncidentDetail(){const {id}=useParams();const {incidents,teams,vehicles,clusters,verifications,assignIncident}=useData();const incident=incidents.find(i=>i.id===id);const [teamId,setTeamId]=useState('');const [vehicleId,setVehicleId]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('')
if(!incident)return <div className="p-8"><Link to="/command/incidents" className="font-bold text-forest-700">← Incident not found</Link></div>
const isSupporting=Boolean(incident.duplicateMasterId);const cluster=clusters.find(c=>c.masterIncidentId===incident.id||c.memberIncidentIds.includes(incident.id));const verification=verifications.find(v=>v.incidentId===incident.id);const assignedTeam=teams.find(t=>t.id===incident.assignedTeamId);const assignedVehicle=vehicles.find(v=>v.id===incident.assignedVehicleId)
const assign=async()=>{setBusy(true);setMessage('');try{await assignIncident(incident.id,teamId,vehicleId);setMessage('Response assigned. The field worker queue has updated.')}catch(err){setMessage(err instanceof Error?err.message:'Could not assign response.')}finally{setBusy(false)}}
const factors=[['Waste volume',incident.scoreBreakdown.volume,25],['Location sensitivity',incident.scoreBreakdown.locationSensitivity,25],['Report frequency',incident.scoreBreakdown.reportFrequency,20],['Complaint age',incident.scoreBreakdown.complaintAge,15],['Hazard / context',incident.scoreBreakdown.hazardContext,15]] as const
return <div className="p-4 sm:p-6 lg:p-8"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div className="flex items-center gap-3"><Link to="/command/priority" className="grid h-10 w-10 place-items-center rounded-lg border border-slate-200 bg-white"><ArrowLeft size={18}/></Link><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-black">{incident.id}</h1><PriorityBadge priority={incident.priorityLevel}/><StatusBadge status={incident.status}/></div><p className="mt-1 text-xs text-slate-500">Reported {timeAgo(incident.createdAt)} · Updated {timeAgo(incident.updatedAt)}</p></div></div>{incident.status==='PRIORITIZED'&&!isSupporting&&<a href="#dispatch"><Button icon={<Truck size={16}/>}>ASSIGN RESPONSE</Button></a>}</div>
<div className="mt-6 grid gap-6 xl:grid-cols-[1.08fr_.92fr]"><div className="space-y-6"><section className="card overflow-hidden rounded-2xl"><div className="flex items-center justify-between border-b border-slate-100 p-4"><div><p className="eyebrow">Before evidence</p><h2 className="mt-1 font-black">Incident image</h2></div><Badge tone="medium">AI regions · prototype</Badge></div><div className="relative overflow-hidden bg-slate-900"><IncidentMedia url={incident.mediaUrl} type={incident.mediaType} controls={incident.mediaType==='video'} className="h-[360px] w-full opacity-95" alt={`Waste at ${incident.address}`}/><div className="absolute left-[12%] top-[35%] h-[43%] w-[66%] border-2 border-dashed border-white/90"><span className="absolute -top-7 left-0 bg-white px-2 py-1 text-[9px] font-bold text-forest-800">{incident.wasteCategory} · {pct(incident.analysis.categories[0].confidence)}</span></div>{incident.analysis.hazardFlags.length>0&&<div className="absolute bottom-4 right-4 flex max-w-xs gap-2 rounded-lg bg-red-700/95 p-3 text-xs font-bold text-white"><AlertTriangle size={16}/>{incident.analysis.hazardFlags[0]}</div>}</div><div className="flex flex-wrap items-center gap-x-5 gap-y-2 p-4 text-xs text-slate-500"><span className="flex items-center gap-1"><MapPin size={14}/>{incident.address}</span><span className="flex items-center gap-1"><Clock3 size={14}/>{shortDate(incident.capturedAt)}</span></div></section>
<section className="card rounded-2xl p-5 sm:p-6"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><BrainCircuit className="text-forest-700" size={20}/><div><p className="eyebrow">WasteVision</p><h2 className="mt-1 text-lg font-black">AI analysis</h2></div></div><span className="rounded-md bg-amber-50 px-2 py-1 text-[9px] font-bold text-amber-800">PROTOTYPE MODEL</span></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><div><p className="label">Waste classification</p><p className="text-lg font-black">{incident.wasteCategory}</p><p className="mt-1 text-xs font-bold text-forest-700">{pct(incident.analysis.categories[0].confidence)} confidence</p></div><div><p className="label">Approximate volume</p><p className="text-lg font-black uppercase">{incident.volumeCategory}</p><p className="mt-1 text-xs font-bold text-forest-700">{pct(incident.analysis.volumeConfidence)} confidence</p></div><div><p className="label">Location sensitivity</p><p className="text-sm font-black">{incident.locationSensitivity}</p><p className="mt-1 text-xs text-slate-500">{incident.sensitivityReason}</p></div><div><p className="label">Potential hazard</p>{incident.analysis.hazardFlags.length?<p className="flex items-center gap-1.5 text-sm font-black text-red-700"><ShieldAlert size={16}/>{incident.analysis.hazardFlags[0]}</p>:<p className="text-sm font-bold text-forest-700">No hazard signal</p>}</div></div><p className="mt-6 rounded-xl bg-slate-50 p-3 text-[11px] leading-5 text-slate-500">AI-assisted operational estimate based on visible waste and contextual evidence. Volume is categorical—not an exact cubic-meter measurement.</p></section>
{verification&&<section className="card overflow-hidden rounded-2xl"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><p className="eyebrow">Closed loop</p><h2 className="mt-1 font-black">Cleanup verification</h2></div><Badge tone={verification.verificationStatus==='VERIFIED'?'success':'high'}>{verification.verificationStatus}</Badge></div><div className="grid sm:grid-cols-2"><div className="relative"><IncidentMedia url={incident.mediaUrl} type={incident.mediaType} className="h-52 w-full" alt="Before-cleanup evidence"/><span className="absolute bottom-2 left-2 rounded bg-black/70 px-2 py-1 text-[9px] font-bold text-white">BEFORE</span></div><div className="relative"><img src={verification.afterMediaPath} className="h-52 w-full object-cover"/><span className="absolute bottom-2 left-2 rounded bg-forest-700 px-2 py-1 text-[9px] font-bold text-white">AFTER</span></div></div><div className="grid grid-cols-2 gap-4 p-5"><div><p className="label">Verification confidence</p><b className="text-2xl text-forest-700">{pct(verification.confidence)}</b></div><div><p className="label">Remaining waste</p><b className="text-2xl text-forest-700">{verification.remainingWasteIndicator}</b></div></div></section>}
<section className="card rounded-2xl p-5 sm:p-6"><p className="eyebrow">Chain of custody</p><h2 className="mt-1 font-black">Incident timeline</h2><div className="mt-6"><StatusTimeline events={incident.timeline} currentStatus={incident.status}/></div></section>
</div><div className="space-y-6"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-card"><div className="bg-forest-800 p-5 text-white"><div className="flex items-center justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-widest text-forest-100">Explainable urgency</p><h2 className="mt-1 text-xl font-black">ActionScore™</h2></div><ScoreRing score={incident.actionScore} size="md"/></div><p className="mt-4 text-xs leading-5 text-forest-100">{explainScore(incident.analysis,incident.sensitivityReason,incident.reportCount)}</p></div><div className="p-5"><div className="space-y-4">{factors.map(([label,value,max])=><div key={label}><div className="flex justify-between text-xs"><span className="font-semibold text-slate-600">{label}</span><b>+{value} <span className="font-normal text-slate-400">/ {max}</span></b></div><div className="mt-2 h-1.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-forest-600" style={{width:`${Math.min(100,value/max*100)}%`}}/></div></div>)}</div><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><span className="text-xs font-bold">Total operational score</span><b className="text-xl">{incident.actionScore} / 100</b></div></div></section>
<section className="card rounded-2xl p-5"><div className="flex items-center gap-2"><Sparkles className="text-forest-700" size={19}/><div><p className="eyebrow">ResponseMatch™</p><h2 className="mt-1 font-black">Recommended response</h2></div></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-4"><Truck size={18} className="text-forest-700"/><p className="mt-3 text-[9px] font-bold uppercase text-slate-400">Vehicle</p><b className="mt-1 block text-sm">{incident.analysis.response.vehicleType}</b></div><div className="rounded-xl bg-slate-50 p-4"><UsersRound size={18} className="text-forest-700"/><p className="mt-3 text-[9px] font-bold uppercase text-slate-400">Crew</p><b className="mt-1 block text-sm">{incident.analysis.response.workerCount} workers</b></div></div>{incident.analysis.response.escalation!=='NONE'&&<div className="mt-3 flex items-center gap-3 rounded-xl border border-red-200 bg-red-50 p-3"><ShieldAlert size={18} className="text-red-700"/><div><p className="text-[9px] font-bold uppercase text-red-600">Escalation</p><b className="text-xs text-red-800">{incident.analysis.response.escalation.replace('_',' ')}</b></div></div>}<div className="mt-4 border-t border-slate-100 pt-4"><p className="label">Decision reason</p><p className="text-xs leading-5 text-slate-600">“{incident.analysis.response.reason}”</p></div></section>
<section className="card rounded-2xl p-5"><div className="flex items-center gap-2"><Network className="text-blue-700" size={19}/><div><p className="text-[10px] font-extrabold uppercase tracking-widest text-blue-700">Duplicate intelligence</p><h2 className="mt-1 font-black">{cluster?`${incident.reportCount} supporting reports`:'No cluster match'}</h2></div></div>{cluster?<><div className="mt-4 space-y-2">{cluster.detectionReason.slice(0,4).map(reason=><p className="flex items-center gap-2 text-xs text-slate-600" key={reason}><Check size={13} className="text-blue-600"/>{reason}</p>)}</div><div className="mt-4 rounded-lg bg-blue-50 p-3 text-xs font-bold text-blue-900">One physical issue → one operational response</div></>:<p className="mt-3 text-xs leading-5 text-slate-500">No active incident passed the configured proximity, time and category threshold.</p>}</section>
<section id="dispatch" className="card rounded-2xl p-5"><div className="flex items-center gap-2"><UserCheck className="text-forest-700"/><div><p className="eyebrow">Dispatch decision</p><h2 className="mt-1 font-black">{isSupporting?'Consolidated response':incident.status==='PRIORITIZED'?'Assign response':'Response assignment'}</h2></div></div>{isSupporting?<div className="mt-5 rounded-xl border border-blue-200 bg-blue-50 p-4"><p className="text-xs font-bold text-blue-900">This record supports master incident {incident.duplicateMasterId}.</p><p className="mt-1 text-[11px] leading-5 text-blue-700">Dispatch is intentionally blocked to prevent duplicate operational responses.</p><Link to={`/command/incidents/${incident.duplicateMasterId}`} className="mt-3 inline-flex items-center gap-1 text-xs font-black text-blue-800">OPEN MASTER INCIDENT →</Link></div>:incident.status==='PRIORITIZED'?<div className="mt-5 space-y-4"><div><label className="label" htmlFor="team">Response team</label><select id="team" value={teamId} onChange={e=>setTeamId(e.target.value)} className="input"><option value="">Select available team</option>{teams.filter(t=>t.availability==='AVAILABLE').map(t=><option value={t.id} key={t.id}>{t.name} · {t.workerCount} workers</option>)}</select></div><div><label className="label" htmlFor="vehicle">Vehicle</label><select id="vehicle" value={vehicleId} onChange={e=>setVehicleId(e.target.value)} className="input"><option value="">Select available vehicle</option>{vehicles.filter(v=>v.availability==='AVAILABLE').map(v=><option value={v.id} key={v.id}>{v.name} · {v.capacity}</option>)}</select></div><Button className="w-full" loading={busy} disabled={!teamId||!vehicleId} icon={<Truck size={16}/>} onClick={()=>void assign()}>CONFIRM & DISPATCH</Button></div>:<div className="mt-5 space-y-3"><div className="rounded-xl bg-forest-50 p-4"><p className="label">Assigned team</p><b className="text-sm">{assignedTeam?.name??'Awaiting resource record'}</b></div><div className="rounded-xl bg-forest-50 p-4"><p className="label">Assigned vehicle</p><b className="text-sm">{assignedVehicle?.name??'Awaiting resource record'}</b></div></div>}{message&&<p role="status" className={`mt-3 rounded-lg p-3 text-xs font-semibold ${message.startsWith('Response')?'bg-forest-50 text-forest-700':'bg-red-50 text-red-700'}`}>{message}</p>}</section>
</div></div></div>}
