import { Activity, ArrowRight, CheckCircle2, CircleAlert, Clock3, Network, Radio, Truck, UsersRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { PriorityBadge, StatusBadge } from '../../components/ui/Badge'
import { useData } from '../../context/DataContext'
import { timeAgo } from '../../lib/utils'

export function Overview(){const {incidents,clusters,assignments,verifications,teams}=useData();const active=incidents.filter(i=>i.status!=='RESOLVED');const critical=active.filter(i=>i.priorityLevel==='CRITICAL');const resolved=incidents.filter(i=>i.status==='RESOLVED');const top=[...active].sort((a,b)=>b.actionScore-a.actionScore).slice(0,5);const wow=incidents.find(i=>i.id==='SW-2048')??top[0];const teamAvailability=[['Available',teams.filter(t=>t.availability==='AVAILABLE').length,'bg-emerald-500'],['Assigned',teams.filter(t=>t.availability==='ASSIGNED').length,'bg-orange-500'],['Off duty',teams.filter(t=>t.availability==='OFF_DUTY').length,'bg-slate-400']] as const
  const chart=Array.from({length:7},(_,index)=>{const d=new Date();d.setDate(d.getDate()-(6-index));const key=d.toLocaleDateString('en',{weekday:'short'});const reports=incidents.filter(i=>new Date(i.createdAt).toDateString()===d.toDateString()).length;return {day:key,reports,resolved:incidents.filter(i=>i.status==='RESOLVED'&&new Date(i.updatedAt).toDateString()===d.toDateString()).length}})
  const kpis=[['Total reports',incidents.length,'Current demo dataset',Radio,'text-blue-700 bg-blue-50'],['Critical',critical.length,'Needs immediate review',CircleAlert,'text-red-700 bg-red-50'],['Duplicate clusters',clusters.length,`${clusters.reduce((s,c)=>s+c.memberIncidentIds.length,0)} linked incidents`,Network,'text-violet-700 bg-violet-50'],['Active responses',assignments.filter(a=>a.status!=='COMPLETED').length,'Across response teams',Truck,'text-orange-700 bg-orange-50'],['Verified cleanup',verifications.filter(v=>v.verificationStatus==='VERIFIED').length,`${resolved.length} incidents resolved`,CheckCircle2,'text-emerald-700 bg-emerald-50'] ] as const
  return <div className="p-4 sm:p-6 lg:p-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="flex items-center gap-2"><span className="eyebrow">Operational picture</span><span className="rounded bg-amber-50 px-2 py-0.5 text-[9px] font-bold text-amber-800">SIMULATED DATA</span></div><h1 className="mt-2 text-2xl font-black tracking-tight sm:text-3xl">Good morning, Operations</h1><p className="mt-2 text-sm text-slate-500">Priorities, resources and response signals across Demo City.</p></div><p className="flex items-center gap-2 text-xs font-semibold text-slate-500"><Clock3 size={15}/>{new Date().toLocaleString([],{dateStyle:'medium',timeStyle:'short'})}</p></div>
    <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{kpis.map(([label,value,note,Icon,style])=><div className="card rounded-xl p-4" key={label}><div className="flex items-start justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-[.12em] text-slate-500">{label}</p><p className="mt-2 text-3xl font-black tracking-tight">{value}</p></div><span className={`grid h-9 w-9 place-items-center rounded-lg ${style}`}><Icon size={18}/></span></div><p className="mt-3 text-[10px] text-slate-500">{note}</p></div>)}</section>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_.55fr]"><section className="card rounded-2xl"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><p className="eyebrow">Decision queue</p><h2 className="mt-1 font-black">Highest operational priority</h2></div><Link to="/command/priority" className="flex items-center gap-1 text-xs font-bold text-forest-700">Full queue <ArrowRight size={14}/></Link></div><div className="divide-y divide-slate-100">{top.map(i=><Link key={i.id} to={`/command/incidents/${i.id}`} className="grid grid-cols-[auto_1fr_auto] items-center gap-3 p-4 transition hover:bg-slate-50 sm:grid-cols-[auto_1.3fr_.8fr_.7fr_auto]"><div className="grid h-11 w-11 place-items-center rounded-lg bg-slate-100 text-sm font-black" style={{color:i.actionScore>=85?'#c93235':'#b7791f'}}>{i.actionScore}</div><div className="min-w-0"><div className="flex items-center gap-2"><b className="text-xs">{i.id}</b><PriorityBadge priority={i.priorityLevel}/></div><p className="mt-1 truncate text-xs font-semibold text-slate-600">{i.wasteCategory} · {i.volumeCategory}</p></div><div className="hidden min-w-0 sm:block"><p className="truncate text-xs font-semibold">{i.address.split('·')[0]}</p><p className="text-[10px] text-slate-400">{timeAgo(i.createdAt)}</p></div><div className="hidden sm:block"><StatusBadge status={i.status}/></div><ArrowRight size={15} className="text-slate-400"/></Link>)}</div></section>
      {wow&&<section className="overflow-hidden rounded-2xl bg-forest-800 p-5 text-white shadow-card"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-widest text-forest-100">Flagship decision</p><h2 className="mt-1 text-xl font-black">ActionScore™</h2></div><Activity className="text-[#86d4b1]"/></div><div className="mt-5 flex items-center gap-5"><div className="grid h-24 w-24 shrink-0 place-items-center rounded-full border-8 border-red-500/80 bg-white text-3xl font-black text-red-600">{wow.actionScore}</div><div><b className="text-sm">{wow.id}</b><p className="mt-1 text-xs leading-5 text-forest-100">{wow.volumeCategory} {wow.wasteCategory.toLowerCase()} · {wow.sensitivityReason}.</p></div></div><div className="mt-5 grid grid-cols-2 gap-2">{[['Volume',wow.scoreBreakdown.volume],['Location',wow.scoreBreakdown.locationSensitivity],['Frequency',wow.scoreBreakdown.reportFrequency],['Age',wow.scoreBreakdown.complaintAge],['Hazard',wow.scoreBreakdown.hazardContext]].map(([k,v])=><div className="flex justify-between rounded-lg bg-white/10 px-3 py-2 text-xs" key={String(k)}><span className="text-forest-100">{k}</span><b>+{v}</b></div>)}</div><Link to={`/command/incidents/${wow.id}`} className="mt-5 flex items-center justify-center gap-2 rounded-lg bg-white py-3 text-xs font-black text-forest-800">Open intelligence <ArrowRight size={14}/></Link></section>}
    </div>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_.55fr]"><section className="card rounded-2xl p-5"><div className="flex justify-between"><div><p className="eyebrow">Demand signal</p><h2 className="mt-1 font-black">Reports over 7 days</h2></div><span className="text-[10px] text-slate-500">Question: when does demand peak?</span></div><div className="mt-5 h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="reports" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#15805f" stopOpacity={.3}/><stop offset="95%" stopColor="#15805f" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#edf0ee"/><XAxis dataKey="day" tickLine={false} axisLine={false} fontSize={10}/><YAxis allowDecimals={false} tickLine={false} axisLine={false} fontSize={10}/><Tooltip/><Area dataKey="reports" stroke="#15805f" strokeWidth={2.5} fill="url(#reports)"/></AreaChart></ResponsiveContainer></div></section>
      <section className="card rounded-2xl p-5"><div className="flex items-center justify-between"><div><p className="eyebrow">Resources</p><h2 className="mt-1 font-black">Team availability</h2></div><UsersRound className="text-forest-700"/></div><div className="mt-6 space-y-4">{teamAvailability.map(([k,v,c])=><div key={String(k)}><div className="flex justify-between text-xs"><span className="font-semibold text-slate-600">{k}</span><b>{v}</b></div><div className="mt-2 h-1.5 rounded-full bg-slate-100"><div className={`h-full rounded-full ${c}`} style={{width:`${teams.length?Number(v)/teams.length*100:0}%`}}/></div></div>)}</div></section>
    </div>
  </div>
}
