import { AlertTriangle, ArrowRight, Filter, Search, SlidersHorizontal, Truck, Users } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { PriorityBadge, StatusBadge } from '../../components/ui/Badge'
import { EmptyState } from '../../components/ui/Loading'
import { useData } from '../../context/DataContext'
import { timeAgo } from '../../lib/utils'

export function PriorityQueue({all=false}:{all?:boolean}){const {incidents}=useData();const [searchParams]=useSearchParams();const [query,setQuery]=useState(()=>searchParams.get('query')??'');const [priority,setPriority]=useState('ALL');const [page,setPage]=useState(1);useEffect(()=>{setQuery(searchParams.get('query')??'');setPage(1)},[searchParams]);const list=useMemo(()=>incidents.filter(i=>all||(i.status!=='RESOLVED'&&!i.duplicateMasterId)).filter(i=>priority==='ALL'||i.priorityLevel===priority).filter(i=>`${i.id} ${i.wasteCategory} ${i.address}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.actionScore-a.actionScore),[incidents,query,priority,all]);const pageSize=8;const pageCount=Math.max(1,Math.ceil(list.length/pageSize));const shown=list.slice((page-1)*pageSize,page*pageSize)
return <div className="p-4 sm:p-6 lg:p-8"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="eyebrow">{all?'Live incident register':'ActionScore-ranked'}</p><h1 className="mt-2 text-2xl font-black sm:text-3xl">{all?'Live incidents':'Priority queue'}</h1><p className="mt-2 text-sm text-slate-500">{list.length} incidents · Sorted by operational urgency, not complaint order.</p></div><div className="flex flex-col gap-2 sm:flex-row"><div className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} className="input min-w-64 py-2.5 pl-9" placeholder="Search incidents…"/></div><div className="relative"><Filter size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><select className="input appearance-none py-2.5 pl-9 pr-8" value={priority} onChange={e=>{setPriority(e.target.value);setPage(1)}}><option>ALL</option><option>CRITICAL</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select></div></div></div>
{!list.length?<div className="mt-8"><EmptyState icon={<SlidersHorizontal/>} title="No matching incidents" description="All critical incidents may be assigned, or your current filters may be too narrow."/></div>:<><div className="mt-7 grid gap-4 xl:grid-cols-2">{shown.map(i=><article key={i.id} className="card overflow-hidden rounded-2xl"><div className="flex border-b border-slate-100"><div className={`grid w-24 shrink-0 place-items-center p-4 ${i.priorityLevel==='CRITICAL'?'bg-red-50':i.priorityLevel==='HIGH'?'bg-orange-50':'bg-amber-50'}`}><div className="text-center"><span className={`block text-3xl font-black ${i.priorityLevel==='CRITICAL'?'text-red-600':i.priorityLevel==='HIGH'?'text-orange-600':'text-amber-700'}`}>{i.actionScore}</span><span className="text-[8px] font-extrabold uppercase tracking-widest text-slate-500">ActionScore</span></div></div><div className="min-w-0 flex-1 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><b>{i.id}</b><PriorityBadge priority={i.priorityLevel}/></div><StatusBadge status={i.status}/></div><h2 className="mt-3 font-black">{i.wasteCategory} · {i.volumeCategory}</h2><p className="mt-1 truncate text-xs text-slate-500">{i.address}</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-[11px] font-semibold text-slate-600"><span>{i.reportCount} supporting {i.reportCount===1?'report':'reports'}</span><span>{timeAgo(i.createdAt)}</span></div></div></div>
<div className="grid gap-4 p-4 sm:grid-cols-[1fr_auto]"><div><p className="text-[9px] font-extrabold uppercase tracking-widest text-forest-700">AI recommendation</p><p className="mt-1 flex items-center gap-2 text-xs font-bold"><Truck size={14}/>{i.analysis.response.vehicleType} <span className="text-slate-300">+</span> <Users size={14}/>{i.analysis.response.workerCount} workers</p>{i.analysis.hazardFlags.length>0&&<p className="mt-2 flex items-center gap-1.5 text-[11px] font-semibold text-red-700"><AlertTriangle size={13}/>{i.analysis.hazardFlags[0]}</p>}</div><Link to={`/command/incidents/${i.duplicateMasterId??i.id}`} className="flex min-h-10 items-center justify-center gap-2 rounded-lg bg-forest-700 px-4 text-xs font-black text-white">{i.duplicateMasterId?'OPEN MASTER':i.status==='PRIORITIZED'?'ASSIGN RESPONSE':'OPEN INCIDENT'}<ArrowRight size={14}/></Link></div></article>)}</div>{pageCount>1&&<nav className="mt-6 flex items-center justify-center gap-3" aria-label="Incident pages"><button disabled={page===1} onClick={()=>setPage(value=>Math.max(1,value-1))} className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-xs font-bold disabled:opacity-40">Previous</button><span className="text-xs font-semibold text-slate-500">Page {page} of {pageCount}</span><button disabled={page===pageCount} onClick={()=>setPage(value=>Math.min(pageCount,value+1))} className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-xs font-bold disabled:opacity-40">Next</button></nav>}</>}
</div>}
